version: '3'
services:
  jekyll:
    image: jekyll/jekyll:latest
    # command: jekyll build
    command: jekyll serve --watch
    ports:
      - 80
    volumes:
      - ./jekyll:/srv/jekyll
  caddy:
    build: ./caddy
    container_name: caddy
    restart: unless-stopped
    env_file:
      - caddy.env
    depends_on:
      - jekyll
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - $PWD/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./jekyll/_site:/srv
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
