version: '3'
services:
  jekyll:
    image: jekyll/jekyll:latest
    command: jekyll build
    # command: jekyll serve --watch --livereload
    ports:
      - 80
    volumes:
      - $PWD/_site:/var/www/html
